### ISSUE TITLE
Code blocks inside list blocks render with 7 spaces instead of 8

### ISSUE THREAD

**Issue by WiredUK** [madskristensen/MarkdownEditor#28]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.5.110

### Description
When rendering a code block that sits inside a number list, the Markdown convention is to indent with 8 spaces (instead of the usual 4), for example:

```
1. Here is item 1
2. Here is list item 2

        This is some code
3. Here is list item 3]
```

However, this extension begins to render the code block after 7 spaces, and includes the extra space as the first character in the code block.

### Steps to recreate
1. Take the text from the code block above and paste it into a Markdown file in VS.
2. Remove 1 space before the `This is some code`
3. Note it is still rendered as code.

**Comment by WiredUK** [comment]
This may not be a bug with the extension but with a library used, perhaps it's an issue with [Markdig](https://github.com/lunet-io/markdig)?

**Comment by xoofx** [comment]
As Markdig is a CommonMark compliant parser, this is a difference with original Markdown. The identation is calculated from the previous list item (where the `Here` starts, so the code indent starts at 4 chars from there) and doesn't use a fixed width as original Markdown. So not really a bug but by design.
