### ISSUE TITLE
Support newline in hyperlinks: [text]\n(uri)

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/MarkdownEditor#59]
### Installed product versions
- Visual Studio: 2015 update 3
- This extension: 1.7.154

### Description
Hyperlinks of form `[,,,](...)` can have a line break in between the sections:

    Here's a wrapped line of text ending in a [link]
    (http://to/some/long/uri).

MarkdownEditor doesn't parse this as a hyperlink. The markdown appears un-decoded in the preview window. GitHub (at least) handles this case correctly.

**Comment by xoofx** [comment]
Unfortunately, a space between `]` and `(` is not commonmark compliant as described in the specs (and very few parsers are actually supporting this.). I suspect that this is done like this in order to disambiguate with forward link references (an alone `[link]` not followed by a `(...)`). Note also that in [babelmark](https://babelmark.github.io/?text=Here%27s+a+wrapped+line+of+text+ending+in+a+%5Blink%5D%0A(http%3A%2F%2Fto%2Fsome%2Flong%2Furi).) it shows that most implem won't interpret this as a link.
